PREFIX ac: <https://w3id.org/ac-ontology/aco#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX fn: <http://w3id.org/sparql-generate/fn/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX cc: <http://creativecommons.org/ns#>
PREFIX http: <http://www.w3.org/2011/http#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
GENERATE {
  ?audioClip
      rdf:type ac:AudioClip ;
      dc:title ?title ;
      cc:license ?license ;
      ac:compiled ?artistURI ;
      ac:available_as ?audioFile ;
      rdf:type prov:Entity ;
      prov:wasAttributedTo <http://jamendo.com> .

  ?audioFile rdf:type ac:AudioFile .

  <http://jamendo.com>
      rdf:type prov:Agent, foaf:Organization ;
      foaf:name "Jamendo" .
}
SOURCE <https://api.jamendo.com/v3.0/tracks/?id=$trackId&client_id=$token&format=json> AS ?source
ITERATOR iter:JSONElement(?source,"$.results[*]") AS ?resIterator
WHERE {
  BIND(IRI(fn:JSONPath(?res, "shareurl")) AS ?audioClip)
  BIND(fn:JSONPath(?res, "name") AS ?title)
  BIND(iri(fn:JSONPath(?res, "license_ccurl")) as ?license)
  BIND(IRI(fn:JSONPath(?res, "audiodownload")) AS ?audioFile)
  BIND(fn:JSONPath(?res, "artist_id") AS ?artist_id)
  BIND(iri(CONCAT("http://www.jamendo.com/artist/", ?artist_id)) as ?artistURI)
}
